language: python
python:
- '3.6'

addons:
  postgresql: "9.6"

before_script:
- psql -c 'create database network;' -U postgres

env:
  global:
  - ALLOWED_HOSTS=localhost
  - CONTENT_TYPE_NO_SNIFF=True
  - CORS_WHITELIST="*"
  - DATABASE_URL=postgres://postgres@localhost:5432/network
  - DEBUG=True
  - DJANGO_SECRET_KEY=secret
  - NETWORK_SITE_URL=https://foundation.mozilla.org
  - PULSE_API_DOMAIN=https://network-pulse-api-production.herokuapp.com
  - PULSE_DOMAIN=www.mozillapulse.org
  - RANDOM_SEED=530910203
  - SET_HSTS=False
  - SSL_REDIRECT=False
  - TARGET_DOMAIN=foundation.mozilla.org
  - USE_CLOUDINARY=false
  - USE_S3=False
  - X_FRAME_OPTIONS=DENY
  - XSS_PROTECTION=True
  - PIPENV_VERBOSITY=-1

cache:
  pip: true
  directories:
    - "$HOME/.npm"

# TODOs Maybe add stages to run percy only if the tests worked?
jobs:
  include:
    - name: "Python tests"
      install: ./travis-scripts/python-install.sh
      script:
        - pipenv run flake8 tasks.py network-api/
        - pipenv run coverage run --source './network-api/networkapi' network-api/manage.py test networkapi
      after_success:
        - coveralls
    - name: "npm tests"
      install: ./travis-scripts/npm-install.sh
      script: npm test
